apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: python-app-deployment 
spec: 
  selector: 
    matchLabels: 
      app: python-app
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: 
    metadata: 
      labels: 
        app: python-app 
    spec: 
      containers: 
      - name: python-app
        image: ahiazd/leumi_project:ahiazdpythonapp
        ports: 
        - containerPort: 80
------
kind: Service 
apiVersion: v1 
metadata: 
  name: python-app-service 
spec: 
  selector: 
    app: python-app
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort         
